INSERT INTO redagro.producto (categoria, tipo) VALUES ("Variado","Variado");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Banana");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Cereza");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Ciruela DAggen");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Ciruela amarilla");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Ciruela negra");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Ciruela roja");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Coco");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Damasco");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Durazno amarillo");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Durazno blanco");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Frutilla");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Granada");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Higo");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Kaqui");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Kiwi");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Lima");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Limón");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Mandarina criolla");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Mandarina clementina");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Mandarina ellendale");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Mandarina nova");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Mandarina murcott");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Mandarina okitsu");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Mamón");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Manzana pink lady");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Manzana roja");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Manzana rome");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Manzana verde");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Maracuyá");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Melón amarillo");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Melón escrito");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Melón blanco");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Membrillo");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Naranja jugo");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Naranja ombligo");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Nuez");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Plátano");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Pelón amarillo");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Pelón blanco");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Pera");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Pera abate fetel");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Pera beurré bosc");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Pera roja");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Piña");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Pomelo blanco");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Pomelo ruby star");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Pomelo rosado");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Sandia");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Sandia baby");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Uva blanca");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Uva cereza");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Uva negra");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Frutas","Uva red globe");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Acelga");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Achicoria");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Ají");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Ajo");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Batata");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Berenjena blanca");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Berenjena negra");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Berenjena violeta");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Brócoli");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Calabaza");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Cebolla blanca");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Cebolla roja");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Cebolla superior");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Chaucha");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Chaucha rolliza");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Choclo");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Ciboulette");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Coliflor");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Curcuma");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Escarola fina");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Escarola ancha");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Espinaca");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Hakusai");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Hinojo");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Jengibre");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Lechuga capuchina");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Lechuga francesa");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Lechuga mantecosa");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Lechuga morada");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Lechuga criolla");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Mandioca");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Papa colorada");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Papa negra");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Papa cepillada");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Pepino");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Pimiento amarillo");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Pimiento rojo");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Pimiento verde");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Radicchio");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Remolacha");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Repollo blanco");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Repollo colorado");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Rúcula");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Tomate redondo");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Tomate racimo");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Tomate perita");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Tomate cherry rojo");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Tomate cherry amarillo");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Zanahoria");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Zapallito largo");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Zapallito redondo");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Zapallo coreano");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Zapallo ingles");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Zapallo muscat");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Verduras","Zapallo kuki");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Otros","Miel");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Otros","Pickles");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Otros","Aceitunas negras");
INSERT INTO redagro.producto (categoria, tipo) VALUES ("Otros","Aceitunas verdes");