package app.clases;

import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public abstract class MailSender {
	
	private String to;
	private String from;
	private String contenido_email;
	private String asunto;
	
		
	public void enviarMail() {
		
		// Put recipient’s address
	      String to = this.getTo();

	      // Put sender’s address
	      String from = this.getFrom();
	      final String username = "e1a6da5291164d";//username generated by Mailtrap
	      final String password = "41b011b75c6279";//password generated by Mailtrap

	      // Paste host address from the SMTP settings tab in your Mailtrap Inbox
	      String host = "smtp.mailtrap.io";

	      Properties props = new Properties();
	      props.put("mail.smtp.auth", "true");
	      props.put("mail.smtp.starttls.enable", "true");//it’s optional in Mailtrap  
	      props.put("mail.smtp.host", host);
	      props.put("mail.smtp.port", "2525");// use one of the options in the SMTP settings tab in your Mailtrap Inbox

	      // Get the Session object.
	      Session session = Session.getInstance(props,
	         new javax.mail.Authenticator() {
	            protected PasswordAuthentication getPasswordAuthentication() {
	               return new PasswordAuthentication(username, password);
	    }
	         });

	      try {
	    // Create a default MimeMessage object.
	    Message message = new MimeMessage(session);
	 
	    // Set From: header field 
	    message.setFrom(new InternetAddress(this.getFrom()));
	 
	    // Set To: header field
	    message.setRecipients(Message.RecipientType.TO,
	               InternetAddress.parse(this.getTo()));
	 
	    // Set Subject: header field
	    message.setSubject(this.getAsunto());
	 
	    // Put the content of your message
	    message.setContent(this.getContenido_email(),"text/html");

	    // Send message
	    Transport.send(message);

	    System.out.println("Mail enviado correctamente....");

	      } catch (MessagingException e) {
	         throw new RuntimeException(e);
	      }
	   }

	public String getTo() {
		return to;
	}

	public void setTo(String to) {
		this.to = to;
	}

	public String getFrom() {
		return from;
	}

	public void setFrom(String from) {
		this.from = from;
	}

	public String getContenido_email() {
		return contenido_email;
	}

	public void setContenido_email(String contenido_email) {
		this.contenido_email = contenido_email;
	}

	public String getAsunto() {
		return asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}
		

}
