INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Banana');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Cereza');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Ciruela DAggen');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Ciruela amarilla');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Ciruela negra');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Ciruela roja');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Coco');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Damasco');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Durazno amarillo');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Durazno blanco');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Frutilla');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Granada');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Higo');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Kaqui');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Kiwi');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Lima');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Limón');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Mandarina criolla');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Mandarina clementina');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Mandarina ellendale');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Mandarina nova');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Mandarina murcott');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Mandarina okitsu');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Mamón');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Manzana pink lady');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Manzana roja');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Manzana rome');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Manzana verde');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Maracuyá');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Melón amarillo');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Melón escrito');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Melón blanco');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Membrillo');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Naranja jugo');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Naranja ombligo');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Nuez');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Plátano');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Pelón amarillo');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Pelón blanco');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Pera');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Pera abate fetel');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Pera beurré bosc');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Pera roja');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Piña');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Pomelo blanco');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Pomelo ruby star');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Pomelo rosado');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Sandia');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Sandia baby');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Uva blanca');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Uva cereza');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Uva negra');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('frutas','Uva red globe');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Achicoria');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Ají');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Batata');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Berenjena blanca');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Berenjena negra');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Berenjena violeta');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Brócoli');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Cebolla blanca');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Cebolla roja');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Cebolla superior');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Chaucha');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Chaucha rolliza');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Ciboulette');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Coliflor');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Curcuma');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Escarola fina');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Escarola ancha');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Hakusai');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Hinojo');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Jengibre');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Lechuga capuchina');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Lechuga francesa');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Lechuga mantecosa');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Lechuga morada');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Lechuga criolla');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Mandioca');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Papa colorada');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Papa negra');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Papa cepillada');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Pepino');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Pimiento amarillo');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Pimiento rojo');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Pimiento verde');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Radicchio');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Remolacha');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Repollo blanco');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Repollo colorado');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Tomate redondo');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Tomate racimo');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Tomate perita');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Tomate cherry rojo');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Tomate cherry amarillo');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Zanahoria');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Zapallito largo');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Zapallito redondo');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Zapallo coreano');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Zapallo ingles');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Zapallo muscat');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('verduras','Zapallo kuki');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('otros','Miel');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('otros','Pickles');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('otros','Aceitunas negras');
INSERT INTO redagro.producto (categoria, tipo) VALUES ('otros','Aceitunas verdes');
